services:
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
  server:
    image: farmasiavr-backend
    container_name: fvr-backend
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - PGCONNECTION=postgres://farmasiavr
      - PORT=3001
      - DEFAULT_EMAIL=default@email.org
      - DEFAULT_PASSWORD=default-password
      - REDIS_URL=redis:6379
      - API_TOKEN=''
    ports:
      - 3001:3001
    depends_on:
      - redis
