
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"] 
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test-database
  server:
    image: farmasiavr-backend
    container_name: FarmasiaVR-backend
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - MONGODB_URL=mongodb://root:example@mongo:27017/
      - PORT=3001
      - DEFAULT_EMAIL=default@email.org
      - DEFAULT_PASSWORD=default-password
      - REDIS_HOST=redis
      - SESSION_SECRET=123456789
      - REDIS_URL=redis:6379
    ports:
      - 3001:3001
    depends_on:
      - mongo
      - redis
  