apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: farmasia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_ROOT_USER
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_ROOT_PASSWORD
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_DATABASE
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: farmasia
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
  clusterIP: None