apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmasiavr-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farmasiavr-backend
  template:
    metadata:
      labels:
        app: farmasiavr-backend
    spec:
      containers:
        - name: farmasiavr-backend
          image: juhosii/farmasiavr-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_URL
            - name: DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DEFAULT_EMAIL
            - name: DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DEFAULT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: farmasiavr-backend
spec:
  selector:
    app: farmasiavr-backend
  ports:
    - port: 8080
      targetPort: 3001
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: farmasiavr-backend
  labels:
    type: external
spec:
  host: farmasiavr-backend-ohtuprojekti-staging.ext.ocp-test-0.k8s.it.helsinki.fi
  to:
    kind: Service
    name: farmasiavr-backend
  port:
    targetPort: 8080
  tls:
    termination: edge  
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: bitnami/mongodb:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_ROOT_USER
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_ROOT_PASSWORD
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_DATABASE
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
  clusterIP: None
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MONGODB_URL: 
  MONGODB_ROOT_USER:
  MONGODB_ROOT_PASSWORD:
  MONGODB_DATABASE:
  DEFAULT_EMAIL: 
  DEFAULT_PASSWORD:

  