apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmasiavr-backend
  annotations:
    app.openshift.io/vcs-ref: v1.0
    app.openshift.io/vcs-uri: https://github.com/FarmasiaVR/farmasia-vr-certificate-backend
  labels:
    app.kubernetes.io/part-of: FarmasiaVR
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farmasiavr-backend
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: farmasiavr-backend
        application: farmasiavr-backend
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
    spec:
      containers:
        - name: farmasiavr-backend
          image: image-registry.openshift-image-registry.svc:5000/ohtuprojekti-staging/farmasiavr-backend:v1.0
          ports:
            - containerPort: 3001
              protocol: TCP
          env:
            - name: PORT
              value: "3001"
          envFrom:
            - secretRef:
              name: farmasiavr-secrets
          resources:
            limits:
              cpu: 700m
              memory: 400Mi
            requests:
              cpu: 300m
              memory: 100Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: farmasiavr-backend
  labels:
    application: farmasiavr-backend
spec:
  selector:
    app: farmasiavr-backend
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: farmasiavr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi
  storageClassName: pomppa25-new
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app.kubernetes.io/part-of: FarmasiaVR
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"farmasiavr-backend"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        application: farmasiavr-backend
    spec:
      containers:
        - name: mongo
          image: bitnami/mongodb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
              protocol: TCP
          env:
            - name: MONGODB_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: farmasiavr-secrets
                  key: MONGODB_ROOT_USER
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: farmasiavr-secrets
                  key: MONGODB_ROOT_PASSWORD
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: farmasiavr-secrets
                  key: MONGODB_DATABASE
          volumeMounts:
            - name: farmasiavr-pvc
              mountPath: /data/db
      volumes:
        - name: farmasiavr-pvc
          persistentVolumeClaim:
            claimName: farmasiavr-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    application: farmasiavr-backend
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongo
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    application: farmasiavr-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      securityContext:
        fsGroup: 1001330000
      containers:
        - name: redis
          image: redis:latest
          securityContext:
            runAsUser: 1001330000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 6379
              protocol: TCP
          command:
            - redis-server
          args:
            - --appendonly
            - "yes"
            - --dir
            - /data
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    application: farmasiavr-backend
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
  type: ClusterIP
  ipFamilies:
    - IPv4
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    type: external
  name: farmasiavr-backend
spec:
  host: farmasiavr-backend-ohtuprojekti-staging.ext.ocp-test-0.k8s.it.helsinki.fi
  path: /
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: farmasiavr-backend
    weight: 100
  wildcardPolicy: None
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: farmasiavr-backend
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: farmasiavr-backend-prod
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  runPolicy: Serial
  source:
    contextDir: /
    git:
      ref: main
      uri: https://github.com/FarmasiaVR/farmasia-vr-certificate-backend
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - gitlab:
        secretReference:
          name: farmasiavr-backend-prod-generic-webhook-secret
      type: GitLab
---
apiVersion: v1
kind: Secret
metadata:
  name: farmasiavr-prod-secrets
  labels:
    application: farmasiavr-backend
type: Opaque
data:
