POST http://localhost:3001/farmasiavr/api/certificates/create
Content-Type: application/json
Authorization: default-password

{
  "user": "John Doe",
  "tasks": [
    {
      "taskName": "Task 1",
      "points": 10
    },
    {
      "taskName": "Task 2",
      "points": 15
    }
  ]
}
