name: Deploy to production

on:
  release:
    types: [published]

permissions:
  contents: read
  deployments: write

jobs:
  build-push:
    name: Build and Push to registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: https://opetushallinto.cs.helsinki.fi/farmasiavr
          environment: production

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build
        run: |-
          docker build --tag "farmasiavr/farmasiavr-backend-prod:${{ github.event.release.tag_name }}" --tag "farmasiavr/farmasiavr-backend-prod:latest" -f prod.Dockerfile .
          docker push --all-tags "farmasiavr/farmasiavr-backend-prod"
  gitlab-tag:
    name: Push release tag to version.helsinki.fi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Set up git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
        
      - name: Push to GitLab
        continue-on-error: true
        env:
          HELSINKIFI_TOKEN: ${{ secrets.HELSINKIFI_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${HELSINKIFI_TOKEN}@version.helsinki.fi/farmasiavr/farmasia-vr-certificate-backend.git
          git push gitlab --tags --force
      
      - name: Success
        run: |
          exit 0
