name: Deploy to staging

on:
  push:

jobs:
  build-publish-deploy:
    name: Build and Push to registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build
        run: |-
          docker build --tag "farmasiavr/farmasiavr-backend:$GITHUB_SHA" .
          docker push "farmasiavr/farmasiavr-backend:$GITHUB_SHA"
