name: Deploy to staging

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-publish-deploy:
    name: Build and push to registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build
        run: |-
          docker build --tag "farmasiavr/farmasiavr-backend:latest" .
          docker push "farmasiavr/farmasiavr-backend:latest"
  gitlab:
    name: Push changes to version.helsinki.fi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Push to version.helsinki.fi
        env:
          HELSINKIFI_TOKEN: ${{ secrets.HELSINKIFI_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${HELSINKIFI_TOKEN}@version.helsinki.fi/farmasiavr/farmasia-vr-certificate-backend.git
          git push -u gitlab main