name: Deploy to staging

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-publish-deploy:
    name: Build and push to registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build
        run: |-
          docker build --tag "farmasiavr/farmasiavr-backend:latest" .
          docker push "farmasiavr/farmasiavr-backend:latest"
